### PR TITLE
lint: fix warnings of linter #14

### LINKED ISSUE #14: fix warnings of linter
https://goreportcard.com/report/github.com/opsway/documents#golint

### PR DESCRIPTION
**Pull request by u5surf**
A similar PR may already be submitted!
**Summary**
I fixed golint warnings #14 

**Test plan**
before:
```
$ golint ./...
api/config.go:3:6: exported type Config should have comment or be unexported
api/routers.go:1:1: package comment should be of the form "Package api ..."
api/routers.go:27:6: exported type Route should have comment or be unexported
api/routers.go:34:6: exported type Routes should have comment or be unexported
api/routers.go:36:1: exported function NewHandler should have comment or be unexported
api/routers.go:45:1: exported function NewRouter should have comment or be unexported
api/server.go:9:1: exported function Server should have comment or be unexported
api/action/html-to-pdf.go:9:1: exported function HtmlToPdfGet should have comment or be unexported
api/action/html-to-pdf.go:9:6: func HtmlToPdfGet should be HTMLToPdfGet
api/action/render-template.go:11:6: exported type RenderTemplateRequest should have comment or be unexported
api/action/render-template.go:17:1: exported function RenderTemplate should have comment or be unexported
api/middleware/logger.go:9:1: comment on exported function Logger should be of the form "Logger ..."
cmd/document/document.go:3:6: exported type Document should have comment or be unexported
cmd/document/pdf.go:14:6: exported type Pdf should have comment or be unexported
cmd/document/pdf.go:19:1: exported method Pdf.SetOptions should have comment or be unexported
cmd/document/pdf.go:28:1: exported method Pdf.AddPageFromUrl should have comment or be unexported
cmd/document/pdf.go:28:17: method AddPageFromUrl should be AddPageFromURL
cmd/document/pdf.go:32:1: exported method Pdf.AddPageFromString should have comment or be unexported
cmd/document/pdf.go:36:1: exported method Pdf.AddPage should have comment or be unexported
cmd/document/pdf.go:40:1: exported method Pdf.Render should have comment or be unexported
cmd/document/pdf.go:46:1: exported method Pdf.RenderByContent should have comment or be unexported
cmd/document/pdf.go:56:1: exported method Pdf.RenderByTemplate should have comment or be unexported
cmd/document/pdf.go:79:1: exported function NewPdf should have comment or be unexported
cmd/template/template.go:15:6: exported type Context should have comment or be unexported
cmd/template/template.go:17:6: exported type Template should have comment or be unexported
cmd/template/template.go:24:1: exported method Template.Render should have comment or be unexported
cmd/template/template.go:44:1: exported function NewTemplate should have comment or be unexported
cmd/template/template.go:56:1: exported function GetTemplate should have comment or be unexported
cmd/template/template.go:66:1: exported function BuildTemplates should have comment or be unexported
util/http.go:10:1: exported function GetUrl should have comment or be unexported
util/http.go:10:6: func GetUrl should be GetURL
util/http.go:24:1: exported function IsValidUrl should have comment or be unexported
util/http.go:24:6: func IsValidUrl should be IsValidURL
util/os.go:5:1: exported function Getenv should have comment or be unexported
util/os.go:14:1: exported function IsValidDir should have comment or be unexported
$
```

after:
```
$ golint ./...
$
```

**Closing issues**
Fixes #14

### CODE REVIEW

File: api/action/html-to-pdf.go [hunk 1]
```diff
@@ -6,7 +6,8 @@ import (
 	"github.com/opsway/documents/cmd/document"
 )
 
-func HtmlToPdfGet(w http.ResponseWriter, r *http.Request) {
+// HTMLToPdfGet renders pdf from html
+func HTMLToPdfGet(w http.ResponseWriter, r *http.Request) {
```
Comment (ilyar) [inline api/action/html-to-pdf.go:10]: @u5surf  Please do not rename. There is a certain consistency in the names at the moment, for example `Html`, `Pdf`, `Url`.  If you use style `HTML`, then for consistency you need to do it everywhere `PDF`, `ULR`, for example `HTMLToPDFGet`, but I see no reason to do it.

**Review by ilyar — CHANGES_REQUESTED** [review]

File: api/action/html-to-pdf.go (hunk 1 above)
Comment (ilyar) [reply api/action/html-to-pdf.go:10]: I additionally consulted with colleagues and we came to the conclusion to use abbreviations
, for example `HTML`, `PDF`, `URL`.

Comment (ilyar) [reply api/action/html-to-pdf.go:10]: use `HTMLToPDFGet`

File: api/routers.go [hunk 2]
```diff
@@ -61,7 +65,7 @@ func NewRouter() *mux.Router {
 
 var routes = Routes{
 
-	// swagger:operation GET /html-to-pdf HtmlToPdfGet
+	// swagger:operation GET /html-to-pdf HTMLToPdfGet
```
Comment (ilyar) [inline api/routers.go:68]: use `HTMLToPDFGet`

**Review by ilyar — CHANGES_REQUESTED** [review]

**Review by ilyar — APPROVED** [review]

**Comment by ilyar** [comment]
@u5surf Thank you!
